/********************************************************************************
** Form generated from reading UI file 'ass3widget.ui'
**
** Created by: Qt User Interface Compiler version 5.7.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ASS3WIDGET_H
#define UI_ASS3WIDGET_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>
#include "qdoubleslider.h"

QT_BEGIN_NAMESPACE

class Ui_Ass3Widget
{
public:
    QLabel *label_obj_filename;
    QPushButton *push_file;
    QLabel *label_file;
    QTabWidget *tabWidget;
    QWidget *tab;
    QLabel *label_7;
    QDoubleSpinBox *sb_light_x;
    QDoubleSpinBox *sb_light_y;
    QDoubleSpinBox *sb_light_z;
    QLabel *lb_light_x;
    QLabel *lb_light_y;
    QLabel *lb_light_z;
    QLabel *label_8;
    QDoubleSlider *sb_light_r;
    QLabel *light_r;
    QLabel *l_light_r;
    QDoubleSlider *sb_light_b;
    QLabel *l_light_b;
    QLabel *light_b;
    QDoubleSlider *sb_light_g;
    QLabel *l_light_g;
    QLabel *light_g;
    QDoubleSlider *sb_ambient_r;
    QLabel *l_ambient_b;
    QLabel *label_9;
    QLabel *l_ambient_r;
    QDoubleSlider *sb_ambient_g;
    QDoubleSlider *sb_ambient_b;
    QLabel *ambient_b;
    QLabel *ambient_g;
    QLabel *ambient_r;
    QLabel *l_ambient_g;
    QCheckBox *cb_light_lock;
    QCheckBox *cb_ambient_lock;
    QWidget *tab_3;
    QDoubleSlider *sb_ambient_c_r;
    QLabel *l_ambient_c_b;
    QLabel *label_10;
    QLabel *l_ambient_c_r;
    QDoubleSlider *sb_ambient_c_g;
    QDoubleSlider *sb_ambient_c_b;
    QLabel *ambient_c_b;
    QLabel *ambient_c_g;
    QLabel *ambient_c_r;
    QLabel *l_ambient_c_g;
    QDoubleSlider *sb_diffuse_r;
    QLabel *l_diffuse_b;
    QLabel *label_11;
    QLabel *l_diffuse_r;
    QDoubleSlider *sb_diffuse_g;
    QDoubleSlider *sb_diffuse_b;
    QLabel *diffuse_b;
    QLabel *diffuse_g;
    QLabel *diffuse_r;
    QLabel *l_diffuse_g;
    QDoubleSlider *sb_specular_r;
    QLabel *l_specular_b;
    QLabel *label_12;
    QLabel *l_specular_r;
    QDoubleSlider *sb_specular_g;
    QDoubleSlider *sb_specular_b;
    QLabel *specular_b;
    QLabel *specular_g;
    QLabel *specular_r;
    QLabel *l_specular_g;
    QLabel *label_13;
    QSpinBox *sb_phong;
    QWidget *tab_4;
    QLabel *label_5;
    QSpinBox *spin_fov;
    QDoubleSpinBox *spin_oblscale;
    QLabel *label_4;
    QRadioButton *btn_parallel;
    QLabel *label;
    QSpinBox *spin_plfar;
    QLabel *label_3;
    QDoubleSpinBox *spin_oblangle;
    QSpinBox *spin_pefar;
    QLabel *label_2;
    QRadioButton *btn_perspective;
    QDoubleSpinBox *spin_top;
    QLabel *label_6;
    QWidget *tab_2;
    QLabel *label_texture_filename;
    QPushButton *push_texturefile;
    QCheckBox *cb_show_texture;

    void setupUi(QWidget *Ass3Widget)
    {
        if (Ass3Widget->objectName().isEmpty())
            Ass3Widget->setObjectName(QStringLiteral("Ass3Widget"));
        Ass3Widget->resize(396, 411);
        label_obj_filename = new QLabel(Ass3Widget);
        label_obj_filename->setObjectName(QStringLiteral("label_obj_filename"));
        label_obj_filename->setGeometry(QRect(20, 30, 300, 20));
        QSizePolicy sizePolicy(QSizePolicy::MinimumExpanding, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(label_obj_filename->sizePolicy().hasHeightForWidth());
        label_obj_filename->setSizePolicy(sizePolicy);
        label_obj_filename->setFocusPolicy(Qt::ClickFocus);
        label_obj_filename->setAutoFillBackground(true);
        label_obj_filename->setFrameShape(QFrame::Panel);
        label_obj_filename->setFrameShadow(QFrame::Sunken);
        label_obj_filename->setLineWidth(1);
        label_obj_filename->setScaledContents(false);
        label_obj_filename->setTextInteractionFlags(Qt::LinksAccessibleByMouse|Qt::TextSelectableByKeyboard|Qt::TextSelectableByMouse);
        push_file = new QPushButton(Ass3Widget);
        push_file->setObjectName(QStringLiteral("push_file"));
        push_file->setGeometry(QRect(330, 30, 31, 21));
        QSizePolicy sizePolicy1(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(push_file->sizePolicy().hasHeightForWidth());
        push_file->setSizePolicy(sizePolicy1);
        label_file = new QLabel(Ass3Widget);
        label_file->setObjectName(QStringLiteral("label_file"));
        label_file->setGeometry(QRect(10, 10, 61, 15));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        label_file->setFont(font);
        tabWidget = new QTabWidget(Ass3Widget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(10, 60, 371, 341));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        label_7 = new QLabel(tab);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 10, 141, 16));
        sb_light_x = new QDoubleSpinBox(tab);
        sb_light_x->setObjectName(QStringLiteral("sb_light_x"));
        sb_light_x->setGeometry(QRect(30, 30, 81, 25));
        sb_light_x->setDecimals(1);
        sb_light_x->setMinimum(-1000);
        sb_light_x->setMaximum(1000);
        sb_light_x->setValue(0);
        sb_light_y = new QDoubleSpinBox(tab);
        sb_light_y->setObjectName(QStringLiteral("sb_light_y"));
        sb_light_y->setGeometry(QRect(30, 60, 81, 25));
        sb_light_y->setDecimals(1);
        sb_light_y->setMinimum(-1000);
        sb_light_y->setMaximum(1000);
        sb_light_y->setValue(1);
        sb_light_z = new QDoubleSpinBox(tab);
        sb_light_z->setObjectName(QStringLiteral("sb_light_z"));
        sb_light_z->setGeometry(QRect(30, 90, 81, 25));
        sb_light_z->setDecimals(1);
        sb_light_z->setMinimum(-1000);
        sb_light_z->setMaximum(1000);
        sb_light_z->setValue(5);
        lb_light_x = new QLabel(tab);
        lb_light_x->setObjectName(QStringLiteral("lb_light_x"));
        lb_light_x->setGeometry(QRect(10, 30, 16, 16));
        lb_light_x->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        lb_light_y = new QLabel(tab);
        lb_light_y->setObjectName(QStringLiteral("lb_light_y"));
        lb_light_y->setGeometry(QRect(10, 60, 16, 16));
        lb_light_y->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        lb_light_z = new QLabel(tab);
        lb_light_z->setObjectName(QStringLiteral("lb_light_z"));
        lb_light_z->setGeometry(QRect(10, 90, 16, 16));
        lb_light_z->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_8 = new QLabel(tab);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 120, 141, 16));
        sb_light_r = new QDoubleSlider(tab);
        sb_light_r->setObjectName(QStringLiteral("sb_light_r"));
        sb_light_r->setGeometry(QRect(80, 140, 160, 18));
        sb_light_r->setFocusPolicy(Qt::NoFocus);
        sb_light_r->setMaximum(100);
        sb_light_r->setValue(50);
        sb_light_r->setOrientation(Qt::Horizontal);
        light_r = new QLabel(tab);
        light_r->setObjectName(QStringLiteral("light_r"));
        light_r->setGeometry(QRect(40, 140, 31, 16));
        l_light_r = new QLabel(tab);
        l_light_r->setObjectName(QStringLiteral("l_light_r"));
        l_light_r->setGeometry(QRect(20, 140, 16, 16));
        sb_light_b = new QDoubleSlider(tab);
        sb_light_b->setObjectName(QStringLiteral("sb_light_b"));
        sb_light_b->setGeometry(QRect(80, 180, 160, 18));
        sb_light_b->setFocusPolicy(Qt::NoFocus);
        sb_light_b->setMaximum(100);
        sb_light_b->setValue(50);
        sb_light_b->setOrientation(Qt::Horizontal);
        l_light_b = new QLabel(tab);
        l_light_b->setObjectName(QStringLiteral("l_light_b"));
        l_light_b->setGeometry(QRect(20, 180, 16, 16));
        light_b = new QLabel(tab);
        light_b->setObjectName(QStringLiteral("light_b"));
        light_b->setGeometry(QRect(40, 180, 31, 16));
        sb_light_g = new QDoubleSlider(tab);
        sb_light_g->setObjectName(QStringLiteral("sb_light_g"));
        sb_light_g->setGeometry(QRect(80, 160, 160, 18));
        sb_light_g->setFocusPolicy(Qt::NoFocus);
        sb_light_g->setMaximum(100);
        sb_light_g->setValue(50);
        sb_light_g->setOrientation(Qt::Horizontal);
        l_light_g = new QLabel(tab);
        l_light_g->setObjectName(QStringLiteral("l_light_g"));
        l_light_g->setGeometry(QRect(20, 160, 16, 16));
        light_g = new QLabel(tab);
        light_g->setObjectName(QStringLiteral("light_g"));
        light_g->setGeometry(QRect(40, 160, 31, 16));
        sb_ambient_r = new QDoubleSlider(tab);
        sb_ambient_r->setObjectName(QStringLiteral("sb_ambient_r"));
        sb_ambient_r->setGeometry(QRect(80, 220, 160, 18));
        sb_ambient_r->setFocusPolicy(Qt::NoFocus);
        sb_ambient_r->setMaximum(100);
        sb_ambient_r->setValue(20);
        sb_ambient_r->setOrientation(Qt::Horizontal);
        l_ambient_b = new QLabel(tab);
        l_ambient_b->setObjectName(QStringLiteral("l_ambient_b"));
        l_ambient_b->setGeometry(QRect(20, 260, 16, 16));
        label_9 = new QLabel(tab);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 200, 151, 16));
        l_ambient_r = new QLabel(tab);
        l_ambient_r->setObjectName(QStringLiteral("l_ambient_r"));
        l_ambient_r->setGeometry(QRect(20, 220, 16, 16));
        sb_ambient_g = new QDoubleSlider(tab);
        sb_ambient_g->setObjectName(QStringLiteral("sb_ambient_g"));
        sb_ambient_g->setGeometry(QRect(80, 240, 160, 18));
        sb_ambient_g->setFocusPolicy(Qt::NoFocus);
        sb_ambient_g->setMaximum(100);
        sb_ambient_g->setValue(20);
        sb_ambient_g->setOrientation(Qt::Horizontal);
        sb_ambient_b = new QDoubleSlider(tab);
        sb_ambient_b->setObjectName(QStringLiteral("sb_ambient_b"));
        sb_ambient_b->setGeometry(QRect(80, 260, 160, 18));
        sb_ambient_b->setFocusPolicy(Qt::NoFocus);
        sb_ambient_b->setMaximum(100);
        sb_ambient_b->setValue(20);
        sb_ambient_b->setOrientation(Qt::Horizontal);
        ambient_b = new QLabel(tab);
        ambient_b->setObjectName(QStringLiteral("ambient_b"));
        ambient_b->setGeometry(QRect(40, 260, 31, 16));
        ambient_g = new QLabel(tab);
        ambient_g->setObjectName(QStringLiteral("ambient_g"));
        ambient_g->setGeometry(QRect(40, 240, 31, 16));
        ambient_r = new QLabel(tab);
        ambient_r->setObjectName(QStringLiteral("ambient_r"));
        ambient_r->setGeometry(QRect(40, 220, 31, 16));
        l_ambient_g = new QLabel(tab);
        l_ambient_g->setObjectName(QStringLiteral("l_ambient_g"));
        l_ambient_g->setGeometry(QRect(20, 240, 16, 16));
        cb_light_lock = new QCheckBox(tab);
        cb_light_lock->setObjectName(QStringLiteral("cb_light_lock"));
        cb_light_lock->setGeometry(QRect(270, 140, 70, 17));
        cb_light_lock->setChecked(true);
        cb_ambient_lock = new QCheckBox(tab);
        cb_ambient_lock->setObjectName(QStringLiteral("cb_ambient_lock"));
        cb_ambient_lock->setGeometry(QRect(270, 220, 70, 17));
        cb_ambient_lock->setChecked(true);
        tabWidget->addTab(tab, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        sb_ambient_c_r = new QDoubleSlider(tab_3);
        sb_ambient_c_r->setObjectName(QStringLiteral("sb_ambient_c_r"));
        sb_ambient_c_r->setGeometry(QRect(80, 30, 160, 18));
        sb_ambient_c_r->setFocusPolicy(Qt::NoFocus);
        sb_ambient_c_r->setMaximum(100);
        sb_ambient_c_r->setValue(20);
        sb_ambient_c_r->setOrientation(Qt::Horizontal);
        l_ambient_c_b = new QLabel(tab_3);
        l_ambient_c_b->setObjectName(QStringLiteral("l_ambient_c_b"));
        l_ambient_c_b->setGeometry(QRect(20, 70, 16, 16));
        label_10 = new QLabel(tab_3);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 10, 141, 16));
        l_ambient_c_r = new QLabel(tab_3);
        l_ambient_c_r->setObjectName(QStringLiteral("l_ambient_c_r"));
        l_ambient_c_r->setGeometry(QRect(20, 30, 16, 16));
        sb_ambient_c_g = new QDoubleSlider(tab_3);
        sb_ambient_c_g->setObjectName(QStringLiteral("sb_ambient_c_g"));
        sb_ambient_c_g->setGeometry(QRect(80, 50, 160, 18));
        sb_ambient_c_g->setFocusPolicy(Qt::NoFocus);
        sb_ambient_c_g->setMaximum(100);
        sb_ambient_c_g->setValue(20);
        sb_ambient_c_g->setOrientation(Qt::Horizontal);
        sb_ambient_c_b = new QDoubleSlider(tab_3);
        sb_ambient_c_b->setObjectName(QStringLiteral("sb_ambient_c_b"));
        sb_ambient_c_b->setGeometry(QRect(80, 70, 160, 18));
        sb_ambient_c_b->setFocusPolicy(Qt::NoFocus);
        sb_ambient_c_b->setMaximum(100);
        sb_ambient_c_b->setValue(20);
        sb_ambient_c_b->setOrientation(Qt::Horizontal);
        ambient_c_b = new QLabel(tab_3);
        ambient_c_b->setObjectName(QStringLiteral("ambient_c_b"));
        ambient_c_b->setGeometry(QRect(40, 70, 31, 16));
        ambient_c_g = new QLabel(tab_3);
        ambient_c_g->setObjectName(QStringLiteral("ambient_c_g"));
        ambient_c_g->setGeometry(QRect(40, 50, 31, 16));
        ambient_c_r = new QLabel(tab_3);
        ambient_c_r->setObjectName(QStringLiteral("ambient_c_r"));
        ambient_c_r->setGeometry(QRect(40, 30, 31, 16));
        l_ambient_c_g = new QLabel(tab_3);
        l_ambient_c_g->setObjectName(QStringLiteral("l_ambient_c_g"));
        l_ambient_c_g->setGeometry(QRect(20, 50, 16, 16));
        sb_diffuse_r = new QDoubleSlider(tab_3);
        sb_diffuse_r->setObjectName(QStringLiteral("sb_diffuse_r"));
        sb_diffuse_r->setGeometry(QRect(80, 120, 160, 18));
        sb_diffuse_r->setFocusPolicy(Qt::NoFocus);
        sb_diffuse_r->setMaximum(100);
        sb_diffuse_r->setValue(100);
        sb_diffuse_r->setOrientation(Qt::Horizontal);
        l_diffuse_b = new QLabel(tab_3);
        l_diffuse_b->setObjectName(QStringLiteral("l_diffuse_b"));
        l_diffuse_b->setGeometry(QRect(20, 160, 16, 16));
        label_11 = new QLabel(tab_3);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(10, 100, 141, 16));
        l_diffuse_r = new QLabel(tab_3);
        l_diffuse_r->setObjectName(QStringLiteral("l_diffuse_r"));
        l_diffuse_r->setGeometry(QRect(20, 120, 16, 16));
        sb_diffuse_g = new QDoubleSlider(tab_3);
        sb_diffuse_g->setObjectName(QStringLiteral("sb_diffuse_g"));
        sb_diffuse_g->setGeometry(QRect(80, 140, 160, 18));
        sb_diffuse_g->setFocusPolicy(Qt::NoFocus);
        sb_diffuse_g->setMaximum(100);
        sb_diffuse_g->setValue(80);
        sb_diffuse_g->setOrientation(Qt::Horizontal);
        sb_diffuse_b = new QDoubleSlider(tab_3);
        sb_diffuse_b->setObjectName(QStringLiteral("sb_diffuse_b"));
        sb_diffuse_b->setGeometry(QRect(80, 160, 160, 18));
        sb_diffuse_b->setFocusPolicy(Qt::NoFocus);
        sb_diffuse_b->setMaximum(100);
        sb_diffuse_b->setOrientation(Qt::Horizontal);
        diffuse_b = new QLabel(tab_3);
        diffuse_b->setObjectName(QStringLiteral("diffuse_b"));
        diffuse_b->setGeometry(QRect(40, 160, 31, 16));
        diffuse_g = new QLabel(tab_3);
        diffuse_g->setObjectName(QStringLiteral("diffuse_g"));
        diffuse_g->setGeometry(QRect(40, 140, 31, 16));
        diffuse_r = new QLabel(tab_3);
        diffuse_r->setObjectName(QStringLiteral("diffuse_r"));
        diffuse_r->setGeometry(QRect(40, 120, 31, 16));
        l_diffuse_g = new QLabel(tab_3);
        l_diffuse_g->setObjectName(QStringLiteral("l_diffuse_g"));
        l_diffuse_g->setGeometry(QRect(20, 140, 16, 16));
        sb_specular_r = new QDoubleSlider(tab_3);
        sb_specular_r->setObjectName(QStringLiteral("sb_specular_r"));
        sb_specular_r->setGeometry(QRect(80, 210, 160, 18));
        sb_specular_r->setFocusPolicy(Qt::NoFocus);
        sb_specular_r->setMaximum(100);
        sb_specular_r->setValue(100);
        sb_specular_r->setOrientation(Qt::Horizontal);
        l_specular_b = new QLabel(tab_3);
        l_specular_b->setObjectName(QStringLiteral("l_specular_b"));
        l_specular_b->setGeometry(QRect(20, 250, 16, 16));
        label_12 = new QLabel(tab_3);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(10, 190, 141, 16));
        l_specular_r = new QLabel(tab_3);
        l_specular_r->setObjectName(QStringLiteral("l_specular_r"));
        l_specular_r->setGeometry(QRect(20, 210, 16, 16));
        sb_specular_g = new QDoubleSlider(tab_3);
        sb_specular_g->setObjectName(QStringLiteral("sb_specular_g"));
        sb_specular_g->setGeometry(QRect(80, 230, 160, 18));
        sb_specular_g->setFocusPolicy(Qt::NoFocus);
        sb_specular_g->setMaximum(100);
        sb_specular_g->setValue(100);
        sb_specular_g->setOrientation(Qt::Horizontal);
        sb_specular_b = new QDoubleSlider(tab_3);
        sb_specular_b->setObjectName(QStringLiteral("sb_specular_b"));
        sb_specular_b->setGeometry(QRect(80, 250, 160, 18));
        sb_specular_b->setFocusPolicy(Qt::NoFocus);
        sb_specular_b->setMaximum(100);
        sb_specular_b->setValue(100);
        sb_specular_b->setOrientation(Qt::Horizontal);
        specular_b = new QLabel(tab_3);
        specular_b->setObjectName(QStringLiteral("specular_b"));
        specular_b->setGeometry(QRect(40, 250, 31, 16));
        specular_g = new QLabel(tab_3);
        specular_g->setObjectName(QStringLiteral("specular_g"));
        specular_g->setGeometry(QRect(40, 230, 31, 16));
        specular_r = new QLabel(tab_3);
        specular_r->setObjectName(QStringLiteral("specular_r"));
        specular_r->setGeometry(QRect(40, 210, 31, 16));
        l_specular_g = new QLabel(tab_3);
        l_specular_g->setObjectName(QStringLiteral("l_specular_g"));
        l_specular_g->setGeometry(QRect(20, 230, 16, 16));
        label_13 = new QLabel(tab_3);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 280, 51, 16));
        sb_phong = new QSpinBox(tab_3);
        sb_phong->setObjectName(QStringLiteral("sb_phong"));
        sb_phong->setGeometry(QRect(60, 280, 81, 25));
        sb_phong->setMinimum(1);
        sb_phong->setMaximum(256);
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        label_5 = new QLabel(tab_4);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 30, 91, 21));
        spin_fov = new QSpinBox(tab_4);
        spin_fov->setObjectName(QStringLiteral("spin_fov"));
        spin_fov->setEnabled(true);
        spin_fov->setGeometry(QRect(100, 30, 81, 25));
        spin_fov->setMinimum(20);
        spin_fov->setMaximum(160);
        spin_fov->setValue(90);
        spin_oblscale = new QDoubleSpinBox(tab_4);
        spin_oblscale->setObjectName(QStringLiteral("spin_oblscale"));
        spin_oblscale->setEnabled(false);
        spin_oblscale->setGeometry(QRect(100, 180, 81, 25));
        spin_oblscale->setAutoFillBackground(false);
        spin_oblscale->setMaximum(1);
        spin_oblscale->setSingleStep(0.25);
        label_4 = new QLabel(tab_4);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 210, 91, 21));
        btn_parallel = new QRadioButton(tab_4);
        btn_parallel->setObjectName(QStringLiteral("btn_parallel"));
        btn_parallel->setGeometry(QRect(10, 100, 107, 20));
        btn_parallel->setChecked(false);
        label = new QLabel(tab_4);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 120, 31, 21));
        label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        spin_plfar = new QSpinBox(tab_4);
        spin_plfar->setObjectName(QStringLiteral("spin_plfar"));
        spin_plfar->setEnabled(false);
        spin_plfar->setGeometry(QRect(100, 150, 81, 25));
        spin_plfar->setMinimum(1);
        spin_plfar->setMaximum(10000);
        spin_plfar->setSingleStep(10);
        spin_plfar->setValue(500);
        label_3 = new QLabel(tab_4);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 180, 91, 21));
        spin_oblangle = new QDoubleSpinBox(tab_4);
        spin_oblangle->setObjectName(QStringLiteral("spin_oblangle"));
        spin_oblangle->setEnabled(false);
        spin_oblangle->setGeometry(QRect(100, 210, 81, 25));
        spin_oblangle->setMinimum(15);
        spin_oblangle->setMaximum(75);
        spin_oblangle->setSingleStep(15);
        spin_oblangle->setValue(45);
        spin_pefar = new QSpinBox(tab_4);
        spin_pefar->setObjectName(QStringLiteral("spin_pefar"));
        spin_pefar->setEnabled(true);
        spin_pefar->setGeometry(QRect(100, 60, 81, 25));
        spin_pefar->setMinimum(1);
        spin_pefar->setMaximum(10000);
        spin_pefar->setSingleStep(10);
        spin_pefar->setValue(500);
        label_2 = new QLabel(tab_4);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 150, 31, 21));
        btn_perspective = new QRadioButton(tab_4);
        btn_perspective->setObjectName(QStringLiteral("btn_perspective"));
        btn_perspective->setGeometry(QRect(10, 10, 107, 20));
        btn_perspective->setChecked(true);
        spin_top = new QDoubleSpinBox(tab_4);
        spin_top->setObjectName(QStringLiteral("spin_top"));
        spin_top->setEnabled(false);
        spin_top->setGeometry(QRect(100, 120, 81, 25));
        spin_top->setAutoFillBackground(false);
        spin_top->setDecimals(1);
        spin_top->setMinimum(1);
        spin_top->setSingleStep(0.5);
        spin_top->setValue(1);
        label_6 = new QLabel(tab_4);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 60, 31, 21));
        tabWidget->addTab(tab_4, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        label_texture_filename = new QLabel(tab_2);
        label_texture_filename->setObjectName(QStringLiteral("label_texture_filename"));
        label_texture_filename->setGeometry(QRect(10, 10, 300, 20));
        sizePolicy.setHeightForWidth(label_texture_filename->sizePolicy().hasHeightForWidth());
        label_texture_filename->setSizePolicy(sizePolicy);
        label_texture_filename->setFocusPolicy(Qt::ClickFocus);
        label_texture_filename->setAutoFillBackground(true);
        label_texture_filename->setFrameShape(QFrame::Panel);
        label_texture_filename->setFrameShadow(QFrame::Sunken);
        label_texture_filename->setLineWidth(1);
        label_texture_filename->setScaledContents(false);
        label_texture_filename->setTextInteractionFlags(Qt::LinksAccessibleByMouse|Qt::TextSelectableByKeyboard|Qt::TextSelectableByMouse);
        push_texturefile = new QPushButton(tab_2);
        push_texturefile->setObjectName(QStringLiteral("push_texturefile"));
        push_texturefile->setGeometry(QRect(320, 10, 31, 21));
        sizePolicy1.setHeightForWidth(push_texturefile->sizePolicy().hasHeightForWidth());
        push_texturefile->setSizePolicy(sizePolicy1);
        cb_show_texture = new QCheckBox(tab_2);
        cb_show_texture->setObjectName(QStringLiteral("cb_show_texture"));
        cb_show_texture->setGeometry(QRect(10, 40, 121, 20));
        tabWidget->addTab(tab_2, QString());

        retranslateUi(Ass3Widget);
        QObject::connect(sb_light_r, SIGNAL(doubleValueChanged(double)), light_r, SLOT(setNum(double)));
        QObject::connect(sb_light_g, SIGNAL(doubleValueChanged(double)), light_g, SLOT(setNum(double)));
        QObject::connect(sb_light_b, SIGNAL(doubleValueChanged(double)), light_b, SLOT(setNum(double)));
        QObject::connect(sb_ambient_r, SIGNAL(doubleValueChanged(double)), ambient_r, SLOT(setNum(double)));
        QObject::connect(sb_ambient_g, SIGNAL(doubleValueChanged(double)), ambient_g, SLOT(setNum(double)));
        QObject::connect(sb_ambient_b, SIGNAL(doubleValueChanged(double)), ambient_b, SLOT(setNum(double)));
        QObject::connect(sb_ambient_c_r, SIGNAL(doubleValueChanged(double)), ambient_c_r, SLOT(setNum(double)));
        QObject::connect(sb_ambient_c_g, SIGNAL(doubleValueChanged(double)), ambient_c_g, SLOT(setNum(double)));
        QObject::connect(sb_ambient_c_b, SIGNAL(doubleValueChanged(double)), ambient_c_b, SLOT(setNum(double)));
        QObject::connect(sb_diffuse_r, SIGNAL(doubleValueChanged(double)), diffuse_r, SLOT(setNum(double)));
        QObject::connect(sb_diffuse_g, SIGNAL(doubleValueChanged(double)), diffuse_g, SLOT(setNum(double)));
        QObject::connect(sb_diffuse_b, SIGNAL(doubleValueChanged(double)), diffuse_b, SLOT(setNum(double)));
        QObject::connect(sb_specular_r, SIGNAL(doubleValueChanged(double)), specular_r, SLOT(setNum(double)));
        QObject::connect(sb_specular_g, SIGNAL(doubleValueChanged(double)), specular_g, SLOT(setNum(double)));
        QObject::connect(sb_specular_b, SIGNAL(doubleValueChanged(double)), specular_b, SLOT(setNum(double)));
        QObject::connect(btn_parallel, SIGNAL(toggled(bool)), spin_top, SLOT(setEnabled(bool)));
        QObject::connect(btn_parallel, SIGNAL(toggled(bool)), spin_plfar, SLOT(setEnabled(bool)));
        QObject::connect(btn_parallel, SIGNAL(toggled(bool)), spin_oblscale, SLOT(setEnabled(bool)));
        QObject::connect(btn_parallel, SIGNAL(toggled(bool)), spin_oblangle, SLOT(setEnabled(bool)));
        QObject::connect(btn_perspective, SIGNAL(toggled(bool)), spin_fov, SLOT(setEnabled(bool)));
        QObject::connect(btn_perspective, SIGNAL(toggled(bool)), spin_pefar, SLOT(setEnabled(bool)));

        tabWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(Ass3Widget);
    } // setupUi

    void retranslateUi(QWidget *Ass3Widget)
    {
        Ass3Widget->setWindowTitle(QApplication::translate("Ass3Widget", "3D Studio", Q_NULLPTR));
        label_obj_filename->setText(QApplication::translate("Ass3Widget", "(none)", Q_NULLPTR));
        push_file->setText(QApplication::translate("Ass3Widget", "...", Q_NULLPTR));
        label_file->setText(QApplication::translate("Ass3Widget", "OBJ File", Q_NULLPTR));
        label_7->setText(QApplication::translate("Ass3Widget", "Light source position", Q_NULLPTR));
        sb_light_x->setPrefix(QString());
        lb_light_x->setText(QApplication::translate("Ass3Widget", "x", Q_NULLPTR));
        lb_light_y->setText(QApplication::translate("Ass3Widget", "y", Q_NULLPTR));
        lb_light_z->setText(QApplication::translate("Ass3Widget", "z", Q_NULLPTR));
        label_8->setText(QApplication::translate("Ass3Widget", "Light source intensity", Q_NULLPTR));
        light_r->setText(QApplication::translate("Ass3Widget", "0,00", Q_NULLPTR));
        l_light_r->setText(QApplication::translate("Ass3Widget", "R", Q_NULLPTR));
        l_light_b->setText(QApplication::translate("Ass3Widget", "B", Q_NULLPTR));
        light_b->setText(QApplication::translate("Ass3Widget", "0,00", Q_NULLPTR));
        l_light_g->setText(QApplication::translate("Ass3Widget", "G", Q_NULLPTR));
        light_g->setText(QApplication::translate("Ass3Widget", "0,00", Q_NULLPTR));
        l_ambient_b->setText(QApplication::translate("Ass3Widget", "B", Q_NULLPTR));
        label_9->setText(QApplication::translate("Ass3Widget", "Ambient light intensity", Q_NULLPTR));
        l_ambient_r->setText(QApplication::translate("Ass3Widget", "R", Q_NULLPTR));
        ambient_b->setText(QApplication::translate("Ass3Widget", "0,00", Q_NULLPTR));
        ambient_g->setText(QApplication::translate("Ass3Widget", "0,00", Q_NULLPTR));
        ambient_r->setText(QApplication::translate("Ass3Widget", "0,00", Q_NULLPTR));
        l_ambient_g->setText(QApplication::translate("Ass3Widget", "G", Q_NULLPTR));
        cb_light_lock->setText(QApplication::translate("Ass3Widget", "Lock RGB", Q_NULLPTR));
        cb_ambient_lock->setText(QApplication::translate("Ass3Widget", "Lock RGB", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("Ass3Widget", "Default Light", Q_NULLPTR));
        l_ambient_c_b->setText(QApplication::translate("Ass3Widget", "B", Q_NULLPTR));
        label_10->setText(QApplication::translate("Ass3Widget", "Ambient coefficient", Q_NULLPTR));
        l_ambient_c_r->setText(QApplication::translate("Ass3Widget", "R", Q_NULLPTR));
        ambient_c_b->setText(QApplication::translate("Ass3Widget", "0,00", Q_NULLPTR));
        ambient_c_g->setText(QApplication::translate("Ass3Widget", "0,00", Q_NULLPTR));
        ambient_c_r->setText(QApplication::translate("Ass3Widget", "0,00", Q_NULLPTR));
        l_ambient_c_g->setText(QApplication::translate("Ass3Widget", "G", Q_NULLPTR));
        l_diffuse_b->setText(QApplication::translate("Ass3Widget", "B", Q_NULLPTR));
        label_11->setText(QApplication::translate("Ass3Widget", "Diffuse coefficient", Q_NULLPTR));
        l_diffuse_r->setText(QApplication::translate("Ass3Widget", "R", Q_NULLPTR));
        diffuse_b->setText(QApplication::translate("Ass3Widget", "0,00", Q_NULLPTR));
        diffuse_g->setText(QApplication::translate("Ass3Widget", "0,00", Q_NULLPTR));
        diffuse_r->setText(QApplication::translate("Ass3Widget", "0,00", Q_NULLPTR));
        l_diffuse_g->setText(QApplication::translate("Ass3Widget", "G", Q_NULLPTR));
        l_specular_b->setText(QApplication::translate("Ass3Widget", "B", Q_NULLPTR));
        label_12->setText(QApplication::translate("Ass3Widget", "Specular coefficient", Q_NULLPTR));
        l_specular_r->setText(QApplication::translate("Ass3Widget", "R", Q_NULLPTR));
        specular_b->setText(QApplication::translate("Ass3Widget", "0,00", Q_NULLPTR));
        specular_g->setText(QApplication::translate("Ass3Widget", "0,00", Q_NULLPTR));
        specular_r->setText(QApplication::translate("Ass3Widget", "0,00", Q_NULLPTR));
        l_specular_g->setText(QApplication::translate("Ass3Widget", "G", Q_NULLPTR));
        label_13->setText(QApplication::translate("Ass3Widget", "Phong", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("Ass3Widget", "Default Material", Q_NULLPTR));
        label_5->setText(QApplication::translate("Ass3Widget", "Field of view", Q_NULLPTR));
        label_4->setText(QApplication::translate("Ass3Widget", "Oblique angle", Q_NULLPTR));
        btn_parallel->setText(QApplication::translate("Ass3Widget", "Parallel", Q_NULLPTR));
        label->setText(QApplication::translate("Ass3Widget", "Top", Q_NULLPTR));
        label_3->setText(QApplication::translate("Ass3Widget", "Oblique scale", Q_NULLPTR));
        label_2->setText(QApplication::translate("Ass3Widget", "Far", Q_NULLPTR));
        btn_perspective->setText(QApplication::translate("Ass3Widget", "Perspecti&ve", Q_NULLPTR));
        label_6->setText(QApplication::translate("Ass3Widget", "Far", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("Ass3Widget", "Projection", Q_NULLPTR));
        label_texture_filename->setText(QApplication::translate("Ass3Widget", "(none)", Q_NULLPTR));
        push_texturefile->setText(QApplication::translate("Ass3Widget", "...", Q_NULLPTR));
        cb_show_texture->setText(QApplication::translate("Ass3Widget", "Show Texture", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("Ass3Widget", "Texture", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class Ass3Widget: public Ui_Ass3Widget {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ASS3WIDGET_H
